# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\WAPresence\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(304, 348)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(304, 348))
        MainWindow.setMaximumSize(QtCore.QSize(304, 348))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Projects\\WAPresence\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(128, 128))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SetAPIText = QtWidgets.QLabel(self.centralwidget)
        self.SetAPIText.setGeometry(QtCore.QRect(20, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SetAPIText.setFont(font)
        self.SetAPIText.setTextFormat(QtCore.Qt.MarkdownText)
        self.SetAPIText.setObjectName("SetAPIText")
        self.QR = QtWidgets.QLabel(self.centralwidget)
        self.QR.setGeometry(QtCore.QRect(20, 60, 271, 271))
        self.QR.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.QR.setAlignment(QtCore.Qt.AlignCenter)
        self.QR.setObjectName("QR")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WAPresence - Login"))
        self.SetAPIText.setText(_translate("MainWindow", "Log in to WhatsApp"))
        self.QR.setText(_translate("MainWindow", "Loading..."))
