# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\WAPresence\SpotifyAPISetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetupSpotifyAPIDialog(object):
    def setupUi(self, SetupSpotifyAPIDialog):
        SetupSpotifyAPIDialog.setObjectName("SetupSpotifyAPIDialog")
        SetupSpotifyAPIDialog.resize(432, 191)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SetupSpotifyAPIDialog.sizePolicy().hasHeightForWidth())
        SetupSpotifyAPIDialog.setSizePolicy(sizePolicy)
        SetupSpotifyAPIDialog.setMinimumSize(QtCore.QSize(432, 191))
        SetupSpotifyAPIDialog.setMaximumSize(QtCore.QSize(432, 191))
        SetupSpotifyAPIDialog.setSizeGripEnabled(False)
        SetupSpotifyAPIDialog.setModal(False)
        self.ActionButton = QtWidgets.QDialogButtonBox(SetupSpotifyAPIDialog)
        self.ActionButton.setGeometry(QtCore.QRect(10, 150, 411, 32))
        self.ActionButton.setWhatsThis("")
        self.ActionButton.setOrientation(QtCore.Qt.Horizontal)
        self.ActionButton.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ActionButton.setCenterButtons(True)
        self.ActionButton.setObjectName("ActionButton")
        self.DialogText = QtWidgets.QLabel(SetupSpotifyAPIDialog)
        self.DialogText.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DialogText.setFont(font)
        self.DialogText.setAlignment(QtCore.Qt.AlignCenter)
        self.DialogText.setObjectName("DialogText")
        self.ClientID = QtWidgets.QLineEdit(SetupSpotifyAPIDialog)
        self.ClientID.setGeometry(QtCore.QRect(110, 60, 311, 20))
        self.ClientID.setWhatsThis("")
        self.ClientID.setObjectName("ClientID")
        self.ClientIDLabel = QtWidgets.QLabel(SetupSpotifyAPIDialog)
        self.ClientIDLabel.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.ClientIDLabel.setObjectName("ClientIDLabel")
        self.ClientSecretLabel = QtWidgets.QLabel(SetupSpotifyAPIDialog)
        self.ClientSecretLabel.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.ClientSecretLabel.setObjectName("ClientSecretLabel")
        self.ClientSecret = QtWidgets.QLineEdit(SetupSpotifyAPIDialog)
        self.ClientSecret.setGeometry(QtCore.QRect(110, 90, 311, 20))
        self.ClientSecret.setWhatsThis("")
        self.ClientSecret.setObjectName("ClientSecret")
        self.RedirectURILabel = QtWidgets.QLabel(SetupSpotifyAPIDialog)
        self.RedirectURILabel.setGeometry(QtCore.QRect(20, 120, 71, 21))
        self.RedirectURILabel.setObjectName("RedirectURILabel")
        self.RedirectURI = QtWidgets.QLineEdit(SetupSpotifyAPIDialog)
        self.RedirectURI.setEnabled(False)
        self.RedirectURI.setGeometry(QtCore.QRect(110, 120, 251, 20))
        self.RedirectURI.setWhatsThis("")
        self.RedirectURI.setReadOnly(False)
        self.RedirectURI.setObjectName("RedirectURI")
        self.EditRedirectButton = QtWidgets.QPushButton(SetupSpotifyAPIDialog)
        self.EditRedirectButton.setGeometry(QtCore.QRect(370, 120, 51, 23))
        self.EditRedirectButton.setWhatsThis("")
        self.EditRedirectButton.setObjectName("EditRedirectButton")

        self.retranslateUi(SetupSpotifyAPIDialog)
        self.ActionButton.accepted.connect(SetupSpotifyAPIDialog.accept) # type: ignore
        self.ActionButton.rejected.connect(SetupSpotifyAPIDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetupSpotifyAPIDialog)

    def retranslateUi(self, SetupSpotifyAPIDialog):
        _translate = QtCore.QCoreApplication.translate
        SetupSpotifyAPIDialog.setWindowTitle(_translate("SetupSpotifyAPIDialog", "WAPresence - Setup Spotify API"))
        self.DialogText.setText(_translate("SetupSpotifyAPIDialog", "You need to setup the Spotify API first!"))
        self.ClientIDLabel.setText(_translate("SetupSpotifyAPIDialog", "Client ID:"))
        self.ClientSecretLabel.setText(_translate("SetupSpotifyAPIDialog", "Client Secret:"))
        self.RedirectURILabel.setText(_translate("SetupSpotifyAPIDialog", "Redirect URI:"))
        self.RedirectURI.setText(_translate("SetupSpotifyAPIDialog", "http://localhost:6969/callback"))
        self.EditRedirectButton.setText(_translate("SetupSpotifyAPIDialog", "Edit"))
